[
  {
    "Name": "Ballyfermot Community Civic Centre",
    "Address": "Ballyfermot Rd",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.343281,
    "Longitude": -6.3640609,
    "Phone": "+353 761 07 5000",
    "Email": "ballyfermot@citinfo.ie",
    "Website": "http://centres.citizensinformation.ie/centre.php?cic=Ballyfermot+CIC"
  },
  {
    "Name": "Ballyfermot Garda Station",
    "Address": "Rossmore Ave",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3447535,
    "Longitude": -6.3602418,
    "Phone": "+353 1 666 7200",
    "Email": "",
    "Website": "https://www.garda.ie/en/Contact-Us/Station-Directory/Ballyfermot.html"
  },
  {
    "Name": "Ballyfermot Post Office",
    "Address": "199 Decies Rd",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3413412,
    "Longitude": -6.3725639,
    "Phone": "+353 1 6269801",
    "Email": "",
    "Website": "http://www.anpost.ie/AnPost/"
  },
  {
    "Name": "Ballyfermot Upper Post Office",
    "Address": "Le Fanu Shopping Centre",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3433644,
    "Longitude": -6.3586097,
    "Phone": "+353 1 6267736",
    "Email": "",
    "Website": "http://www.anpost.ie/AnPost/"
  },
  {
    "Name": "Ballyfermot Youth Service Gurteen Youth Club",
    "Address": "Gurteen Park",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3306394,
    "Longitude": -6.3792416,
    "Phone": "+353 1 623 1431",
    "Email": "info@ballyfermotys.ie",
    "Website": "http://www.ballyfermotyouthservice.ie/contact-us/"
  },
  {
    "Name": "Ballyfermot Youth Service Head Office",
    "Address": "41 Decies Rd",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3457143,
    "Longitude": -6.3526856,
    "Phone": "+353 1 623 1431",
    "Email": "admin@ballyfermotys.ie",
    "Website": "http://www.ballyfermotyouthservice.ie/contact-us/"
  },
  {
    "Name": "Ballyfermot Youth Service Information Centre",
    "Address": "Drumfinn Park",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3463828,
    "Longitude": -6.3561269,
    "Phone": "+353 1 623 7401",
    "Email": "info@ballyfermotys.ie",
    "Website": "http://www.ballyfermotyouthservice.ie/contact-us/"
  },
  {
    "Name": "Bank of Ireland",
    "Address": "Drumfinn",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3424872,
    "Longitude": -6.3538015,
    "Phone": "+353 1 626 8124",
    "Email": "contactus@boi.com",
    "Website": "https://www.bankofireland.com"
  },
  {
    "Name": "Cherry Orchard Park",
    "Address": "Cherry Orchard",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3360144,
    "Longitude": -6.3728064,
    "Phone": "",
    "Email": "",
    "Website": ""
  },
  {
    "Name": "Claddagh Green Post Office",
    "Address": "15 Claddagh Green",
    "Town": "Cherry Orchard",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3406909,
    "Longitude": -6.3684037,
    "Phone": "+353 1 6265716",
    "Email": "",
    "Website": "http://www.anpost.ie/AnPost/"
  },
  {
    "Name": "Kylemore Park",
    "Address": "Kylemore Avenue",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3384617,
    "Longitude": -6.3512943,
    "Phone": "+353 1 6265051",
    "Email": "",
    "Website": ""
  },
  {
    "Name": "Markiewicz Park",
    "Address": "Ballyfermot Decies Rd.",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.341007,
    "Longitude": -6.3399075,
    "Phone": "+353 1 222 2222",
    "Email": "",
    "Website": ""
  },
  {
    "Name": "Permanent TSB",
    "Address": "Unit 3/4 Tesco Shopping Centre Ballyfermot Rd. Drumfinn",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3424872,
    "Longitude": -6.3548958,
    "Phone": "+353 1 212 4101",
    "Email": "info@permanenttsb.ie",
    "Website": "https://www.permanenttsb.ie/"
  }
]