[
  {
    "Name": "Babes In The Wood Creche",
    "Address": "10 Cedar Brook Walk",
    "Town": "",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3368853,
    "Longitude": -6.3803117,
    "Phone": "+353 1 620 8580",
    "Website": "www.babesinthewoodcreche.com",
    "Email": "mail@babesinthewoodscreche.com"
  },
  {
    "Name": "Ballyfermot Chapelizod Partnership",
    "Address": "4 Drumfinn Park Drumfinn",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3441442,
    "Longitude": -6.3591914,
    "Phone": "+353 1 623 5612",
    "Website": "http://www.bcpartnership.ie/",
    "Email": "info@bcpartnership.ie"
  },
  {
    "Name": "Ballyfermot Resource Centre",
    "Address": "Lynch's Ln. Chapelizod",
    "Town": "",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3429701,
    "Longitude": -6.3481017,
    "Phone": "+353 1 626 4147",
    "Website": "www.ballyfermotfrc.com/",
    "Email": "info@ballyfermotfrc.com"
  },
  {
    "Name": "Ballyfermot Youth Service",
    "Address": "3 Drumfinn Park Drumfinn",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3441374,
    "Longitude": -6.361521,
    "Phone": "+353 1 605 5011",
    "Website": "http://www.ballyfermotyouthservice.ie/",
    "Email": "info@ballyfermotys.ie"
  },
  {
    "Name": "CDETB Ballyfermot Training Centre",
    "Address": "Ballyfermot Hill Chapelizod",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3468992,
    "Longitude": -6.3499903,
    "Phone": "+353 1 605 5900",
    "Website": "http://www.ballyfermottrainingcentre.ie/",
    "Email": "barecruitment@btc.cdetb.ie"
  },
  {
    "Name": "De La Salle Boys National School",
    "Address": "89-91 Ballyfermot Rd Chapelizod",
    "Town": "",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3210673159,
    "Longitude": -6.3747406314,
    "Phone": "+353 1 626 7527",
    "Website": "",
    "Email": "delasalleballyfermot@gmail.com"
  },
  {
    "Name": "Kylemore Community Training Centre",
    "Address": "1st Floor Ballyfermot Family Resource Centre",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3427759,
    "Longitude": -6.3466536,
    "Phone": "+353 1 623 1356",
    "Website": "https://ballyfermotfrc.com/kylemore-community-training-centre/",
    "Email": "info@kylemorectc.ie"
  },
  {
    "Name": "Saint Ultans",
    "Address": "Cherry Orchard Ave. Cherry Orchard",
    "Town": "Cherry Orchard Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3370779,
    "Longitude": -6.3757047,
    "Phone": "+353 1 643 4599",
    "Website": "www.stultans.ie/saint-ultans-primary-school/",
    "Email": "office@Stultans.ie"
  },
  {
    "Name": "St Gabriels Primary School",
    "Address": "159 Ballyfermot Rd.",
    "Town": "",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3429787,
    "Longitude": -6.3466287,
    "Phone": "+353 1 626 5958",
    "Website": "www.stgabrielsprimary.ie",
    "Email": "office@stgabrielsprimary.ie"
  },
  {
    "Name": "St Matthews Preschool",
    "Address": "5 Drumfinn Park",
    "Town": "",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3427874,
    "Longitude": -6.366042,
    "Phone": "+353 1 626 5695",
    "Website": "www.stmatthewsballyfermot.com",
    "Email": ""
  },
  {
    "Name": "St. Michael's N.S",
    "Address": "R112 Chapelizod",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3431442,
    "Longitude": -6.3504625,
    "Phone": "+353 1 626 3556",
    "Website": "www.stmichaelsns.blogspot.ie/",
    "Email": "stmichaelns.ias@eircom.net"
  },
  {
    "Name": "St. Raphaels National School",
    "Address": "199 Kylemore Rd. Chapelizod",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3431958,
    "Longitude": -6.3498501,
    "Phone": "+353 1 626 5953",
    "Website": "www.straphaels.ie/",
    "Email": "info@straphaels.ie"
  },
  {
    "Name": "St.Gabriels Primary School",
    "Address": "159 Ballyfermot Rd. Chapelizod",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Postcode": "Dublin 10",
    "Latitude": 53.3428777,
    "Longitude": -6.3486584,
    "Phone": "+353 1 626 5958",
    "Website": "www.stgabrielsprimary.ie",
    "Email": "office@stgabrielsprimary.ie"
  }
]