[
  {
    "Name": "Ballyfermot Dental Practice",
    "Address": "276 Ballyfermot Rd. Drumfinn",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3426413,
    "Longitude": -6.3532344,
    "Phone": "+353 1 626 5776",
    "Website": "http://www.ballyfermotdentalpractice.ie/",
    "Email": "ballyfermotdentalpractice3@gmail.com"
  },
  {
    "Name": "Ballyfermot Dental Surgery",
    "Address": "Unit 10 Le Fanu Shopping Centre Le Fanu Rd.",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3432152,
    "Longitude": -6.3559215,
    "Phone": "+353 1 626 6204",
    "Website": "",
    "Email": ""
  },
  {
    "Name": "Ballyfermot Family Practice",
    "Address": "Ballyfermot Family Practice Ballyfermot Rd,",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3430026,
    "Longitude": -6.3608377,
    "Phone": "+353 1 626 6238",
    "Website": "",
    "Email": ""
  },
  {
    "Name": "Ballyfermot Pharmacy",
    "Address": "Tesco Shopping Centre Ballyfermot Rd. Kylemore",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3418507,
    "Longitude": -6.3530094,
    "Phone": "+353 1 616 6111",
    "Website": "",
    "Email": ""
  },
  {
    "Name": "Ballyfermot Primary Care Centre",
    "Address": "Ballyfermot Rd Cherry Orchard",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.343314,
    "Longitude": -6.3717323,
    "Phone": "+353 76 695 6000",
    "Website": "",
    "Email": ""
  },
  {
    "Name": "Boylan's Pharmacy Ltd",
    "Address": "9 Claddagh Green Cherry Orchard",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3409367,
    "Longitude": -6.3661185,
    "Phone": "+353 1 626 4988",
    "Website": "",
    "Email": ""
  },
  {
    "Name": "Claddagh Surgery",
    "Address": "Ballyfermot Primary Care Centre Ballyfermot Cherry Orchard",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.343311,
    "Longitude": -6.371518,
    "Phone": "+353 76 695 6012",
    "Website": "https://claddaghsurgery.ie/",
    "Email": "reception@claddaghsurgery.ie"
  },
  {
    "Name": "Crowleys Pharmacy",
    "Address": "207 Decies Rd. Decies",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.340844,
    "Longitude": -6.349347,
    "Phone": "+353 1 626 4528",
    "Website": "",
    "Email": ""
  },
  {
    "Name": "Dr. Donal P O'Sullivan",
    "Address": "203 Le Fanu Road",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3418742,
    "Longitude": -6.3589533,
    "Phone": "+353 1 626 6238",
    "Website": "",
    "Email": ""
  },
  {
    "Name": "Emile Evans Dentist",
    "Address": "283 Ballyfermot Rd. Kylemore",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3419842,
    "Longitude": -6.35295,
    "Phone": "+353 1 623 2268",
    "Website": "",
    "Email": ""
  },
  {
    "Name": "Grange Cross Medical Centre",
    "Address": "Grange Cross Ballyfermot Rd",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3426553,
    "Longitude": -6.3566796,
    "Phone": "+353 1 626 4762",
    "Website": "",
    "Email": ""
  },
  {
    "Name": "Kiely's CarePlus Pharmacy",
    "Address": "282 Ballyfermot Rd",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3423791,
    "Longitude": -6.3515802,
    "Phone": "+353 1 626 0800",
    "Website": "https://www.careplus.ie/pharmacies/Kielys282-CarePlus-Pharmacy-Dublin",
    "Email": "kielys.ballyfermot@careplus.ie"
  },
  {
    "Name": "Lloyds Pharmacy",
    "Address": "292 Ballyfermot Rd",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3421452,
    "Longitude": -6.3524278,
    "Phone": "+353 1 623 8434",
    "Website": "https://www.lloydspharmacy.ie/",
    "Email": "onlinesupport@LloydsPharmacy.ie"
  },
  {
    "Name": "Moloneys Pharmacy",
    "Address": "Grange Cross Drumfinn",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3425612,
    "Longitude": -6.3565396,
    "Phone": "+353 1 626 4131",
    "Website": "www.sites.google.com/site/moloneyspharmacy/contact-us",
    "Email": ""
  },
  {
    "Name": "The Surgery",
    "Address": "314b Ballyfermot Rd Drumfinn",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3423271,
    "Longitude": -6.3543754,
    "Phone": "+353 1 626 2629",
    "Website": "http://www.docvadis.ie/naseema-moorad/index.html",
    "Email": "drmooradsurgery@gmail.com"
  },
  {
    "Name": "Your Local Pharmacy",
    "Address": "3 Ballyfermot Rd. Drumfinn",
    "Town": "Ballyfermot",
    "County": "Dublin",
    "Post Code": "Dublin 10",
    "Latitude": 53.3425362,
    "Longitude": -6.3542209,
    "Phone": "+353 1 626 3180",
    "Website": "www.facebook.com/yourlocalpharmacygroup/",
    "Email": ""
  }
]