[
  {
    "Name": "Ballyfermot DLS GAA club",
    "Address": "Gurteen Rd. Drumfinn",
    "Town": "Ballyfermot",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.342379,
    "Longitude": -6.33894,
    "Phone": "+353 85 168 7280",
    "Website": "www.ballyfermotdls.altervista.org/",
    "Email": "donorekarateclub@gmail.com"
  },
  {
    "Name": "Ballyfermot Leisure Centre",
    "Address": "Blackditch Rd. Cherry Orchard",
    "Town": "Ballyfermot",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.3411046,
    "Longitude": -6.3597487,
    "Phone": "+353 1 222 8580",
    "Website": "www.dublincity.ie/main-menu-services-recreation-culture-sports-facilities-leisure-centres-leisure-centre-locations-0",
    "Email": ""
  },
  {
    "Name": "Ballyfermot Sports Complex Ltd",
    "Address": "Gurteen Rd.",
    "Town": "Ballyfermot",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.3466478,
    "Longitude": -6.3653541,
    "Phone": "+353 1 626 9213",
    "Website": "ballyfermotsportscomplex@gmail.com",
    "Email": "www.facebook.com/ballyfermotsportscomplex1985/"
  },
  {
    "Name": "Ballyfermot United Sports & Social Club",
    "Address": "2 Blackditch Rd.",
    "Town": "Cherry Orchard",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.3418221,
    "Longitude": -6.357472,
    "Phone": "+353 1 626 7584",
    "Website": "www.bussc.ie/about-us/",
    "Email": "info@bussc.ie"
  },
  {
    "Name": "Black Dragon Shotokan Karate Club",
    "Address": "2-58 Blackditch Rd.",
    "Town": "Cherry Orchard",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.3411237,
    "Longitude": -6.3578754,
    "Phone": "+353 87 121 9129",
    "Website": "www.blackdragonshotokan.webs.com/",
    "Email": ""
  },
  {
    "Name": "Cherry Orchard Equine Centre",
    "Address": "Cherry Orchard Green",
    "Town": "Cherry Orchard",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.33813,
    "Longitude": -6.379388,
    "Phone": "+353 1 620 9160",
    "Website": "www.cherryorchard.ie",
    "Email": "reception@cherryorchard.ie"
  },
  {
    "Name": "Colosseum Gym",
    "Address": "Kylemore Park S. Kylemore",
    "Town": "Ballyfermot",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.3335928,
    "Longitude": -6.3504409,
    "Phone": "+353 1 623 8616",
    "Website": "www.colossuemgym.ie",
    "Email": ""
  },
  {
    "Name": "Commercial Rowing Club Dublin",
    "Address": "Longmeadows Islandbridge Phoenix Park",
    "Town": "Ballyfermot",
    "Country": "Dublin",
    "Post code": "Dublin 8",
    "Latitude": 53.3463011,
    "Longitude": -6.322141,
    "Phone": "+353 87 249 7146",
    "Website": "www.commercialrc.ie",
    "Email": ""
  },
  {
    "Name": "Donore Karate Club",
    "Address": "20 Chapelizod Rd. Chapelizod",
    "Town": "Chapelizod",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.3451034,
    "Longitude": -6.3486863,
    "Phone": "+353 85 840 5506",
    "Website": "www.donorekarateclub.com/",
    "Email": ""
  },
  {
    "Name": "Longmeadows Pitch And Putt Course",
    "Address": "253 Sarsfield Rd. Ballyfermot Chapelizod",
    "Town": "Ballyfermot",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.343407,
    "Longitude": -6.335715,
    "Phone": "+353 1 630 4380",
    "Website": "www.longmeadowspitchandputt.ie",
    "Email": ""
  },
  {
    "Name": "Parkwest Swimming Pool",
    "Address%uFFFD": "The Plaza Parkwest Avenue Nangor Road",
    "Town": "Ballyfermot",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.3319274,
    "Longitude": -6.3703375,
    "Phone": "+353 85 876 1647",
    "Website": "www.parkwestswimmingpool.ie",
    "Email": ""
  },
  {
    "Name": "Sarsfield Racing Pigeon Club",
    "Address": "Lally Rd. Kilmainham",
    "Town": "Ballyfermot",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.3425352,
    "Longitude": -6.3377994,
    "Phone": "+353 1 626 4916",
    "Website": "",
    "Email": ""
  },
  {
    "Name": "St. Matthews Boxing Club",
    "Address": "Drumfinn Rd. Drumfinn",
    "Town": "Ballyfermot",
    "Country": "Dublin",
    "Post code": "Dublin 10",
    "Latitude": 53.3460922,
    "Longitude": -6.3614818,
    "Phone": "+353 87 278 0316",
    "Website": "www.stmatthewsboxingclub.com",
    "Email": ""
  }
]